theme: jekyll-theme-cayman
gems: ["jemoji"]
title: AVL
description: 加速孵化新創 Startup Incubator
google_analytics: UA-140600686-5
splash_btn_text: 查看職缺
job_form_url: https://forms.gle/uuvw3TYH2YpZvT5m9
exam_submit_form_url: https://forms.gle/LW9UAo2YWpUrgFLq6
link_jd_culture: "/principles/principles.html"
link_jd_benefits: "/people/benefits.html"
link_jd_salary: "/people/engineering_level.html"
link_jd_projectfee: "/people/projectbased_level.html"
link_jd_interview_process: "/recruit/interview_process.html"
link_jd_expectations: "/principles/values.html"
link_team: "/team.html"
link_onboarding: "/recruit/onboarding.html"
link_fullstack_training: "/people/fullstack_training.html"
link_sample_fullstackdev: "/recruit/sample_fullstackdev.html"
link_engineering: "/engineering/engineering.html"
user_g: G
user_d: D
exclude:
    - _main/
    - ie8n.py
    - Gemfile
    - Gemfile.lock
    - README.md
#https://github.com/letrastudio/jekyll-i18n/blob/master/_config.yml

locales:
    default:
        baseurl: "/zh-tw"
        name: 繁體中文
        lang: zh-tw
    zh-cn:
        baseurl: /zh-cn
        name: 简体中文
        lang: zh-cn
    en:
        baseurl: "/en"
        name: English
        lang: en
collections:
    pages_zh-tw:
        output: true
        permalink: /zh-tw/:path
    pages_zh-cn:
        output: true
        permalink: /zh-cn/:path
    pages_en:
        output: true
        permalink: /en/:path
